[general]
timeout = "5s"
hot_reload_rebounce_timer = "100ms"

[[handler]]
on = "openwindow"
when = "swaync"
then = "width=$(( $(hyprctl monitors | awk 'NR == 2 {print $1; exit}' | awk -F 'x' 'NR ==1 {print $1; exit}') - 300 )) && notify-send $width && hyprctl dispatch resizeactive exact $width 100%"
